### PR TITLE
Add feature "Go To Last Tab"

### PR DESCRIPTION
**Pull request by htyleo**
With regard to issue #1, I add the feature "Go To Last Tab" by revising just several lines of code.

Awesome work!

### CODE REVIEW

**Comment by jiripospisil** [comment]
Thank you for the PR! I'll test it out over the weekend.

**Comment by jiripospisil** [comment]
Works like a charm. Thanks.

**Comment by jiripospisil** [comment]
Alright, the new release (1.3) has been approved and should be available :+1:.

**Comment by htyleo** [comment]
Great! Thanks :)

**Pull request merged**
